server:
  port: 8080


#awsCognitoPoolId: us-east-1_RS1UPfitM
#awsCognitoClientId: 7jgae8od6snn1lijrvgl7fnrhh
#awsCognitoRegion: us-east-1

awsCognitoPoolId: ${awsCognitoPoolId}
awsCognitoClientId: ${awsCognitoClientId}
awsCognitoRegion: ${awsCognitoRegion}
  
spring:
#  h2:
#    console:
#      enabled: true
      
  datasource:
#Base de datos Mysql
#Configuración Local
#     url: jdbc:mysql://localhost:3306/encuestabd?useUnicode=true&characterEncoding=utf8&useSSL=false&requireSSL=false&serverTimezone=UTC
#     username: root
#     password: 123456
#Configuración Enviroment
     url: jdbc:mysql://${host}:${port}/${database}?useUnicode=true&characterEncoding=utf8&useSSL=false&requireSSL=false&serverTimezone=UTC
     username: ${username}
     password: ${password}
  
#Base de datos H2
#    url: jdbc:h2:mem:encuestaDB:DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#    driverClassName: org.h2.Driver
#    platform: h2
#    username: sa
#    password: 
    
  jpa:
    show-sql: true
    hibernate:
#      ddl-auto: update
      ddl-auto: none
#    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: false
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"